name: Upgrade nx workspace

on:
  workflow_dispatch:

jobs:
  upgrade-packages:
    name: Upgrade nx workspace

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Upgrade nx 🔀
        run: |
          npm i
          npx nx migrate latest


      - name: Create Commit 💌
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "build(deps): upgrade nx (automated)" --no-verify

      - name: Create PR 🔀
        uses: peter-evans/create-pull-request@v4
        with:
          title: "build(deps): Upgrade nx (automated)"
          branch: "build-deps-upgrade-nx-automated"
          commit-message: "build(deps): upgrade nx (automated)"
          labels: "dependencies"
