name: Upgrade NPM packages with pr

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrade-packages:
    name: Upgrade packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache dependencies ⚙️
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Upgrade packages 🔀
        run: |
          rm -f package-lock.json
          npm i
          npm i

      - name: Create Commit 💌
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "build(deps): upgrade NPM packages (automated)" --no-verify

      - name: Create PR 🔀
        uses: peter-evans/create-pull-request@v4
        with:
          title: "build(deps): Upgrade NPM packages (automated)"
          branch: "build-deps-upgrade-npm-packages-automated"
          commit-message: "build(deps): upgrade NPM packages (automated)"
          labels: "dependencies"
